'use client'

import { useState, useEffect, useCallback } from 'react'
import { useSearchParams } from 'next/navigation'
import { createClient } from '../../../lib/supabase'
import { Suspense } from 'react'

function ReportContent() {
  const supabase = createClient()
  const params = useSearchParams()
  const [data, setData] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const start = params.get('start') || ''
  const end   = params.get('end')   || ''

  const load = useCallback(async () => {
    const { data: { session } } = await supabase.auth.getSession()
    if (!session) { setError('Not authenticated'); setLoading(false); return }
    const q = new URLSearchParams()
    if (start) q.set('start', start)
    if (end)   q.set('end', end)
    const res = await fetch(`/api/owner/payroll/report?${q}`, {
      headers: { Authorization: `Bearer ${session.access_token}` }
    })
    const json = await res.json()
    if (json.error) { setError(json.error); setLoading(false); return }
    setData(json)
    setLoading(false)
  }, [start, end])

  useEffect(() => { load() }, [load])

  const fmt = (n: number) => `$${n.toFixed(2)}`
  const fmtH = (n: number) => `${n.toFixed(2)}`
  const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })

  if (loading) return <div style={{ padding: '4rem', textAlign: 'center', fontFamily: 'Georgia, serif', color: '#555' }}>Generating report...</div>
  if (error)   return <div style={{ padding: '4rem', textAlign: 'center', color: 'red' }}>Error: {error}</div>
  if (!data)   return null

  const { company, period, employees, totals } = data

  const periodLabel = period.start && period.end
    ? `${new Date(period.start).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })} — ${new Date(period.end).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`
    : 'All time (approved entries)'

  return (
    <div style={{ fontFamily: 'Georgia, "Times New Roman", serif', background: '#fff', color: '#111', minHeight: '100vh' }}>
      {/* Print button — hidden when printing */}
      <div className="no-print" style={{ background: '#1a1a1a', padding: '0.875rem 2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <span style={{ color: '#aaa', fontSize: '0.875rem' }}>Payroll Report Preview — <strong style={{ color: '#fff' }}>{company.name}</strong></span>
        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button
            onClick={() => window.print()}
            style={{ background: '#00d9ff', color: '#000', border: 'none', padding: '0.5rem 1.25rem', borderRadius: '6px', fontWeight: '700', cursor: 'pointer', fontSize: '0.875rem' }}
          >
            🖨 Print / Save PDF
          </button>
          <button
            onClick={() => window.close()}
            style={{ background: 'transparent', color: '#555', border: '1px solid #333', padding: '0.5rem 1rem', borderRadius: '6px', cursor: 'pointer', fontSize: '0.875rem' }}
          >
            ✕ Close
          </button>
        </div>
      </div>

      {/* Report */}
      <div style={{ maxWidth: '900px', margin: '0 auto', padding: '3rem 2.5rem' }}>

        {/* Header */}
        <div style={{ borderBottom: '3px solid #111', paddingBottom: '1.5rem', marginBottom: '1.5rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div>
              <div style={{ fontSize: '1.75rem', fontWeight: '700', letterSpacing: '-0.02em' }}>{company.name}</div>
              <div style={{ fontSize: '1rem', color: '#555', marginTop: '0.25rem' }}>Payroll Summary Report</div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <div style={{ fontSize: '0.875rem', color: '#555' }}>Generated by TimeClok</div>
              <div style={{ fontSize: '0.875rem', color: '#555' }}>{today}</div>
            </div>
          </div>
        </div>

        {/* Period info */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1.5rem', marginBottom: '2rem', padding: '1.25rem', background: '#f8f8f8', borderRadius: '6px', border: '1px solid #e0e0e0' }}>
          <div>
            <div style={{ fontSize: '0.72rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.06em', color: '#888', marginBottom: '0.25rem' }}>Pay Period</div>
            <div style={{ fontSize: '0.9rem', fontWeight: '600' }}>{periodLabel}</div>
          </div>
          <div>
            <div style={{ fontSize: '0.72rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.06em', color: '#888', marginBottom: '0.25rem' }}>Pay Schedule</div>
            <div style={{ fontSize: '0.9rem', fontWeight: '600', textTransform: 'capitalize' }}>{company.paySchedule}</div>
          </div>
          <div>
            <div style={{ fontSize: '0.72rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.06em', color: '#888', marginBottom: '0.25rem' }}>Total Employees</div>
            <div style={{ fontSize: '0.9rem', fontWeight: '600' }}>{employees.length}</div>
          </div>
        </div>

        {/* Payroll table */}
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.875rem', marginBottom: '2rem' }}>
          <thead>
            <tr style={{ background: '#111', color: '#fff' }}>
              {['Employee', 'Type', 'Position', 'Reg Hrs', 'OT Hrs', 'Total Hrs', 'Rate', 'Reg Pay', 'OT Pay', 'Gross Pay', 'Deductions', 'Net Pay'].map(h => (
                <th key={h} style={{ padding: '0.75rem 0.875rem', textAlign: h === 'Employee' || h === 'Type' || h === 'Position' ? 'left' : 'right', fontWeight: '700', fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.04em', whiteSpace: 'nowrap' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {employees.map((emp: any, i: number) => {
              const regPay = emp.regularHours * emp.hourlyRate
              const otPay  = emp.overtimeHours * emp.hourlyRate * 1.5
              return (
                <tr key={emp.id} style={{ background: i % 2 === 0 ? '#fff' : '#fafafa', borderBottom: '1px solid #e8e8e8' }}>
                  <td style={{ padding: '0.75rem 0.875rem' }}>
                    <div style={{ fontWeight: '600' }}>{emp.name}</div>
                    <div style={{ fontSize: '0.72rem', color: '#888' }}>{emp.email}</div>
                  </td>
                  <td style={{ padding: '0.75rem 0.875rem' }}>
                    <span style={{ background: emp.employeeType === 'w2' ? '#dbeafe' : '#dcfce7', color: emp.employeeType === 'w2' ? '#1e40af' : '#166534', padding: '0.15rem 0.5rem', borderRadius: '4px', fontSize: '0.72rem', fontWeight: '700', textTransform: 'uppercase' }}>
                      {emp.employeeType}
                    </span>
                  </td>
                  <td style={{ padding: '0.75rem 0.875rem', color: '#555' }}>{emp.position || '—'}</td>
                  <td style={{ padding: '0.75rem 0.875rem', textAlign: 'right' }}>{fmtH(emp.regularHours)}</td>
                  <td style={{ padding: '0.75rem 0.875rem', textAlign: 'right', color: emp.overtimeHours > 0 ? '#dc2626' : '#888' }}>
                    {emp.overtimeHours > 0 ? fmtH(emp.overtimeHours) : '—'}
                  </td>
                  <td style={{ padding: '0.75rem 0.875rem', textAlign: 'right', fontWeight: '600' }}>{fmtH(emp.totalHours)}</td>
                  <td style={{ padding: '0.75rem 0.875rem', textAlign: 'right' }}>${emp.hourlyRate.toFixed(2)}</td>
                  <td style={{ padding: '0.75rem 0.875rem', textAlign: 'right' }}>{fmt(regPay)}</td>
                  <td style={{ padding: '0.75rem 0.875rem', textAlign: 'right', color: otPay > 0 ? '#dc2626' : '#888' }}>{otPay > 0 ? fmt(otPay) : '—'}</td>
                  <td style={{ padding: '0.75rem 0.875rem', textAlign: 'right', fontWeight: '700' }}>{fmt(emp.grossPay)}</td>
                  <td style={{ padding: '0.75rem 0.875rem', textAlign: 'right', color: '#888' }}>{emp.deductions > 0 ? fmt(emp.deductions) : '—'}</td>
                  <td style={{ padding: '0.75rem 0.875rem', textAlign: 'right', fontWeight: '700' }}>{fmt(emp.netPay)}</td>
                </tr>
              )
            })}
          </tbody>
          {/* Totals row */}
          <tfoot>
            <tr style={{ background: '#111', color: '#fff', borderTop: '2px solid #111' }}>
              <td colSpan={3} style={{ padding: '0.875rem', fontWeight: '700', fontSize: '0.875rem' }}>TOTALS</td>
              <td style={{ padding: '0.875rem', textAlign: 'right', fontWeight: '700' }}>{fmtH(totals.regularHours)}</td>
              <td style={{ padding: '0.875rem', textAlign: 'right', fontWeight: '700' }}>{totals.overtimeHours > 0 ? fmtH(totals.overtimeHours) : '—'}</td>
              <td style={{ padding: '0.875rem', textAlign: 'right', fontWeight: '700' }}>{fmtH(totals.totalHours)}</td>
              <td style={{ padding: '0.875rem' }}></td>
              <td style={{ padding: '0.875rem', textAlign: 'right', fontWeight: '700' }}>{fmt(totals.grossPay - totals.overtimeHours * 0)}</td>
              <td style={{ padding: '0.875rem', textAlign: 'right', fontWeight: '700' }}></td>
              <td style={{ padding: '0.875rem', textAlign: 'right', fontWeight: '700', fontSize: '1rem' }}>{fmt(totals.grossPay)}</td>
              <td style={{ padding: '0.875rem', textAlign: 'right', fontWeight: '700' }}>{totals.deductions > 0 ? fmt(totals.deductions) : '—'}</td>
              <td style={{ padding: '0.875rem', textAlign: 'right', fontWeight: '700', fontSize: '1rem' }}>{fmt(totals.netPay)}</td>
            </tr>
          </tfoot>
        </table>

        {/* Summary boxes */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1rem', marginBottom: '2.5rem' }}>
          {[
            { label: 'Total Hours Worked', value: `${fmtH(totals.totalHours)} hrs` },
            { label: 'Total Gross Payroll', value: fmt(totals.grossPay) },
            { label: 'Total Net Payroll', value: fmt(totals.netPay) },
          ].map(s => (
            <div key={s.label} style={{ border: '2px solid #111', borderRadius: '6px', padding: '1rem 1.25rem' }}>
              <div style={{ fontSize: '0.72rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.06em', color: '#888', marginBottom: '0.35rem' }}>{s.label}</div>
              <div style={{ fontSize: '1.5rem', fontWeight: '700' }}>{s.value}</div>
            </div>
          ))}
        </div>

        {/* Notes */}
        <div style={{ marginBottom: '2.5rem', padding: '1rem 1.25rem', border: '1px solid #e0e0e0', borderRadius: '6px', fontSize: '0.8rem', color: '#555' }}>
          <strong style={{ color: '#111' }}>Notes for accountant:</strong>
          <ul style={{ margin: '0.5rem 0 0 1.25rem', lineHeight: '1.8' }}>
            <li>All hours shown are approved by the employer. Overtime calculated at 1.5x for hours exceeding 40/week.</li>
            <li>W-2 employees are subject to standard payroll tax withholdings. 1099 contractors are responsible for self-employment taxes.</li>
            <li>This report was generated by TimeClok workforce management software.</li>
          </ul>
        </div>

        {/* Signature lines */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '3rem', marginTop: '3rem', paddingTop: '1.5rem', borderTop: '1px solid #ddd' }}>
          {['Employer Signature', 'Accountant / Preparer Signature'].map(label => (
            <div key={label}>
              <div style={{ borderBottom: '1px solid #111', marginBottom: '0.5rem', height: '2.5rem' }}></div>
              <div style={{ fontSize: '0.78rem', color: '#555' }}>{label}</div>
              <div style={{ borderBottom: '1px solid #ccc', marginBottom: '0.5rem', height: '1.75rem', marginTop: '1rem' }}></div>
              <div style={{ fontSize: '0.78rem', color: '#555' }}>Date</div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div style={{ marginTop: '2rem', paddingTop: '1rem', borderTop: '1px solid #eee', textAlign: 'center', fontSize: '0.72rem', color: '#aaa' }}>
          Generated by TimeClok · timeclok.vercel.app · {today}
        </div>
      </div>

      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { margin: 0; }
        }
      `}</style>
    </div>
  )
}

export default function PayrollReportPage() {
  return (
    <Suspense fallback={<div style={{ padding: '4rem', textAlign: 'center' }}>Loading...</div>}>
      <ReportContent />
    </Suspense>
  )
}
